ci: add gobject-introspection to fix virt-install runtime error
Fedora virt-install tests are failing with the error:
gi.RepositoryError: Typelib file for namespace 'libxml2', version '2.0' not found

This adds the missing dependency as a workaround.

Signed-off-by: Paul Whalen <pwhalen@fedoraproject.org>